config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do 

    get 'terms', to: "pages#terms"

    get 'privacy', to: "pages#privacy"

    get 'about', to: "pages#about"

    devise_scope :podcast do
     get "signup", to: "devise/registrations#new"
     get "signin", to: "devise/sessions#new"
     get "signout", to: "devise/sessions#destroy"
    end

    devise_for :podcasts

    resources :podcasts, only: [:index, :show] do 
    	resources :episodes
    end

    authenticated :podcast do 
    	root 'podcasts#dashboard', as: "authenticated_root"
    end

    root 'welcome#index' 
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '',      to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :podcasts
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast
  belongs_to :category

  has_attached_file :episode_thumbnail, styles: { large: "1000x1000#", medium: "550x550#", thumb: "100x100>" }
  validates_attachment_content_type :episode_thumbnail, content_type: /\Aimage\/.*\z/

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => {:content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/]}
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :episodes

  has_attached_file :thumbnail, styles: { large: "1000x1000#", medium: "550x550#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :set_locale 

private 

  def set_locale
  	I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay, :thumbnail)}
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title, :thumbnail)}
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :authenticate_podcast!, except: [:show]
	before_action :require_permission, except: [:show]
	before_action :find_podcast
	before_action :find_episode, only: [:show, :edit, :update, :destroy]

	def new
		@episode = @podcast.episodes.new
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@episode = @podcast.episodes.new episode_params

		@episode.category_id = params[:category_id]

		if @episode.save
			redirect_to podcast_episode_path(@podcast, @episode)
		else
			render 'new'
		end
	end

	def show
		@episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").limit(6).reject{ |e| e.id ==  @episode.id}
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@episode.category_id = params[:category_id]
		
		if @episode.update episode_params
			redirect_to podcast_episode_path(@podcast, @episode, notice: "Episode was succesfully updated")
		else
			render 'edit'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end


	private

	def episode_params
		params.require(:episode).permit(:title, :description, :episode_thumbnail, :mp3, :category_id)
	end

	def find_podcast
		@podcast = Podcast.find(params[:podcast_id])
	end

	def find_episode
		@episode = Episode.find(params[:id])
	end

	def require_permission
		@podcast = Podcast.find(params[:podcast_id])
		if current_podcast != @podcast
			redirect_to root_path, notice: "Sorry, you're not allowed to see this page"
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def privacy
  end

  def about
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

	before_action :find_podcast, only: [:show, :dashboard]
	before_action :find_episode, only: [:show, :dashboard]

	def index
		@podcasts = Podcast.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
	end

	def show
	end

	def dashboard
		
	end

	private 

	def find_episode
		@episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
	end

	def find_podcast
		if params[:id].nil?
			@podcast = current_podcast
		else
			@podcast = Podcast.find(params[:id])
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/episodes/_form.html.erb
<%= form_for ([@podcast, @episode]) do |f| %>
	<div class="field">
		<%= f.label :title %> <br />
		<%= f.text_field :title %> <br />
	</div>
	<div class="field">
		<%= f.label :description %> <br />
		<%= f.text_area :description %> <br />
	</div>

	<div class="field">
		<%= f.label :description %> <br />
		<%= f.text_area :description %> <br />
	</div>

	<div class="field">
		<%= f.label "Category" %> <br />
		<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select A Category") %> <br />
	</div>

	<div class="field">
		<%= f.label :mp3 %> <br />
		<%= f.file_field :mp3 %> <br />
	</div>

	<%= f.submit "Add Episode", class: "button button_highlight button_block" %>

<% end %>

app/views/episodes/edit.html.erb
 <!-- Banner Section -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
    <h1>The Rocketship Podcast Dashboard</h1>
  </div>
     </div>
     <!-- Banner End -->

  <!-- Dashboard Link Section -->
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path  %></li>
        <li><%= link_to "New Episode", new_podcast_episode_path(@podcast)%></li>
        <li><%= link_to "Account Settings",edit_podcast_registration_path%></li>
        <li><%= link_to "View Podcasts", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>
</div>  

<div id="form">
  <div class="wrapper_skinny">



  <%= render 'form' %>
</div>
</div>  

app/views/episodes/new.html.erb
 <!-- Banner Section -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
    <h1> لوحة التحكم</h1>
  </div>
     </div>
     <!-- Banner End -->

  <!-- Dashboard Link Section -->
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "التدوينات", root_path %></li>
        <li><%= link_to "تدوينة جديدة", new_podcast_episode_path(@podcast), class: "current"%></li>
        <li><%= link_to "اعدادات الحساب",edit_podcast_registration_path%></li>
        <li><%= link_to "اظهار التدوينات", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>
</div>  

<div id="form">
  <div class="wrapper_skinny">

<h1>New Episode</h1>

  <%= render 'form' %>
</div>
</div>

app/views/episodes/show.html.erb
	   <!-- Banner Section -->
		<div id="podcast_show">
			<div id="show_banner">
				<div class="wrapper_skinny">
				<h1><%= @podcast.title %></h1>
				<p class="description">
					<%= @podcast.description %>
				</p>
				<% unless @podcast.itunes.blank? %>
					<a href="<%= @podcast.itunes%>" class="subscribe_link" target="_blank">iTunes</a>
				<% end %>
				<% unless @podcast.stitcher.blank? %>
					<a href="<%= @podcast.stitcher %>" class="subscribe_link" target="_blank">Stitcher</a>
				<% end %>
				<% unless @podcast.podbay.blank? %>
					<a href="<%= @podcast.podbay %>" class="subscribe_link" target="_blank">PodBay</a>
				<% end %>
					<a href="<%= @podcast.podbay %>" class="subscribe_link" target="_blank"><%= @episode.category.name%></a>
			</div>
	  	   </div>
	  	   <!-- Banner End -->

			<!-- Breadcrumb Section -->
	  	   <div id="breadcrumb">
	  	   <%= link_to podcasts_path do%>
	  	   All Podcasts 
	  	   	<span> / </span>
	  	   	<%= link_to @podcast.title, podcast_path(@podcast) %>
	  	   	<span> / </span>
	  	   	<%= @episode.title %>
	  	   <% end %>
	  	   </div>
		  </div>
			<!-- Breadcrumb End -->

		<div id="episode_content">
				<div class="wrapper_skinny">
				<%= image_tag @episode.episode_thumbnail.url(:medium), class: "current_episode_thumbnail" %>
					<h2><%= @episode.title %></h2>
					<p class="description">
						<%= @episode.description %>
					</p>

					<div id="jquery_jplayer_1" class="jp-jplayer"></div>
					<div id="jp_container_1" class="jp-audio">
						<div class="jp-type-single">
							<div class="jp-gui jp-interface">
							<ul class="jp-controls">
								<li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
								<li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
								<li><a href="javascript:;" class="jp-mute" tabindex="1">&#61480;</a></li>
								<li><a href="javascript:;" class="jp-unmute" tabindex="1">&#61478;</a></li>
							</ul>
							<div class="jp-progress">
								<div class="jp-seek-bar">
									<div class="jp-play-bar"></div>
								</div>
							</div>

							<div class="jp-time-holder">
								<div class="jp-current-time"></div>
							</div>

							<div class="jp-volume-bar">
								<div class="jp-volume-bar-value"></div>
							</div>

							<div class="jp-no-solution">
								<span>Update Required</span>
								To play all the media on your browser  you have to update the version of it <a href="https://get.adoe.com/flashplayer/" target="_blank">Flash plugin</a>
							</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<!-- Breadcrumb End -->

			<div id="episodes">
				<div class="wrapper_skinny">
					<ul class="cf">


					<!-- Article Item -->
					<% @episodes.each do |episode| %>
						<li class="cf">
							<div class="episode_thumbnail">
								<a href="#">
								<%= image_tag episode.episode_thumbnail.url(:medium), class: "current_episode_thumbnail" %>
								</a>
							</div>
							<div class="episode_overview">
								<h2>
									<%= link_to episode.title, podcast_episode_path(@podcast, episode) %>
								</h2>
								<p class="description">
									<%= truncate(episode.description, length:160) %>
								</p>
							</div>
						</li>
					<% end %>
					<!-- Article Item ends -->

					</ul>
				</div>
			</div>

<script>
	$(document).ready(function(){
		$("#jquery_jplayer_1").jPlayer({
			ready: function () {
				$(this).jPlayer("setMedia", {
					mp3: "<%= @episode.mp3.url %>",
				});
			},
			swfPath: "/js",
			supplied: "mp3"
		});
	});
</script>

app/views/layouts/_footer.html.erb
  <footer id="footer">
	<div class="wrapper_wide">
	<a id="logo" href="/">نسحة تجريبية</a>
	<nav>
		<ul>
			<li><%= link_to "شروط الاستخدام", terms_path %></li>
			<li><%= link_to "سياسة الخصوصية", privacy_path %></li>
			<li><a href="">اتصل بنا</a></li>			
			<li><%= link_to "حول", about_path %></li>
		</ul>
	</nav>
   </div>
  </footer>

app/views/layouts/_header.html.erb
  <header class="cf" id="main_header">
    <div class="wrapper_wide">
    <%= link_to t("navbar.logo"), root_path, id: "logo" %>
      <nav>
        <ul>
        <% unless podcast_signed_in? %>
          <li><%= link_to t("navbar.menu.explore"), podcasts_path%></li>
          <li><%= link_to t("navbar.menu.signin"), signin_path  %></li>
          <li><%= link_to t("navbar.menu.signup"), signup_path %></li> 
          <%= link_to_unless_current "العربية", locale: "ar" %> | 
          <%= link_to_unless_current "English", locale: "en" %>
        <% else %>
          <li><%= link_to t("navbar.menu.dashboard"), root_path %></li>
          <li><%= link_to t("navbar.menu.explore"), podcasts_path %></li>
          <li><%= link_to t("navbar.menu.signout"), destroy_podcast_session_path, method: :delete %>
          <% end %>
        </ul>
      </nav>
       </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>قلم صوتك 🎹</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//fonts.googleapis.com/css?family=Cairo:400,700" rel="stylesheet"><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>

  <% if alert %>
    <div id="notice_wrapper">
  	   <p class="alert"><%= alert %></p>
    </div>
  <% elsif notice %>
    <div id="notice_wrapper">
    	<p class="notice"><%= notice %></p>
    </div>
  <% end %>

    <!-- Header & Navigation -->
    <% unless current_page?(root_path) %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <script>
    "use strict";
    $(document).ready(function(){
      setTimeout(function(){
        $('#notice_wrapper').fadeOut("slow", function(){
          $('#notice_wrapper').remove();
        });
      },4500);
    });
      
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Banner section -->
<div id="banner" class="signin_banner">
  <h1><%= t "pages.about.brand" %></h1>
</div>

<div class="wrapper_wide">
	<div id="box">
		<h1>معلومات حول المنصة</h1>
	</div>
</div>

app/views/pages/privacy.html.erb
<!-- Banner section -->
<div id="banner" class="signup_banner">
  <h1> سياسة الخصوصية</h1>
</div>

<div class="wrapper_wide">
	<div id="box">
		<h1>سياسة الخصوصية</h1>
	</div>
</div>

app/views/pages/terms.html.erb
<!-- Banner section -->
<div id="banner" class="podcasts_banner">
  <h1><%= t "pages.terms.brand" %></h1>
</div>	

<div class="wrapper_wide">
	<div id="box">
		<h1>شروط الاستخدام</h1>
	</div>
</div>

app/views/podcasts/dashboard.html.erb
<%= render 'layouts/header' %>
 <!-- Banner Section -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
    <h1> لوحة التحكم</h1>
  </div>
     </div>
     <!-- Banner End -->

  <!-- Dashboard Link Section -->
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "التدوينات", root_path, class: "current"  %></li>
        <li><%= link_to "تدوينة جديدة", new_podcast_episode_path(@podcast)%></li>
        <li><%= link_to "اعدادات الحساب",edit_podcast_registration_path%></li>
        <li><%= link_to "اظهار التدوينات", podcast_path(current_podcast) %></li>
      </ul>
    </div>
  </div>
</div> 

      <div id="episodes">
        <div class="wrapper_skinny">
          <ul class="cf">

          <!-- Article Item -->
          <% @episodes.each do |episode| %>
            <li class="cf">
              <div class="episode_thumbnail">
                <a href="#">
                <%= image_tag episode.episode_thumbnail.url(:medium)%>
                </a>
              </div>
              <div class="episode_overview">
                <h2>
                  <%= link_to episode.title, podcast_episode_path(@podcast, episode)%>
                </h2>
                <p class="description">
                  <%= truncate(episode.description, length: 160) %>
                </p>
                <div class="authorized_links">
                <%= link_to "تعديل", edit_podcast_episode_path(@podcast,episode) %>
                <%= link_to "حذف", podcast_episode_path(@podcast,episode), method: :delete, data: {confirm: "هل انت متأكد انك تريد حذف هذه التدوينة ؟"} %>
                </div>
              </div>
            </li>
            <% end %>
          <!-- Article Item ends -->
          
          </ul>
        </div>
      </div>

        <!-- Pagination -->
        <%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/podcasts/index.html.erb
<!-- Banner section -->
		<div id="banner" class="podcasts_banner">
			<h1>. اكتشاف مدونتك الشخصية المفضلة الجديدة</h1>
		</div>
		
		<!-- Podcasts section -->
		<div id="podcasts" class="cf">
			<div class="wrapper">
				<ul class="cf">
					<% @podcasts.each do |podcast| %>
						<%= link_to podcast do %>
						<li>
							<%= image_tag podcast.thumbnail.url(:medium) %>
							<div class="podcast_overview">
								<h2><%= podcast.title %></h2>
								<p class="episode_count">1 Episode</p>
							</div>
						</li>
						<% end %>
				   <% end%>
				</ul>
				<%= will_paginate @podcasts, previous_label: "Previous", next_label: "Next" %>
			</div>
		</div>

		<!-- Podcasts ends -->

app/views/podcasts/show.html.erb
	   <!-- Banner Section -->
		<div id="podcast_show">
			<div id="show_banner">
				<div class="wrapper_skinny">
				<h1><%= @podcast.title %></h1>
				<p class="description">
					<%= @podcast.description %>
				</p>
				<% unless @podcast.itunes.blank? %>
					<a href="<%= @podcast.itunes%>" class="subscribe_link" target="_blank">iTunes</a>
				<% end %>
				<% unless @podcast.stitcher.blank? %>
					<a href="<%= @podcast.stitcher %>" class="subscribe_link" target="_blank">Stitcher</a>
				<% end %>
				<% unless @podcast.podbay.blank? %>
					<a href="<%= @podcast.podbay %>" class="subscribe_link" target="_blank">PodBay</a>
				<% end %>
			</div>
	  	   </div>
	  	   <!-- Banner End -->

			<!-- Breadcrumb Section -->
	  	   <div id="breadcrumb">
	  	   <%= link_to podcasts_path do%>
	  	   All Podcasts 
	  	   	<span> / </span>
	  	   	<%= @podcast.title %>
	  	   <% end %>
	  	   </div>
		  </div>
			<!-- Breadcrumb End -->

			<div id="episodes">
				<div class="wrapper_skinny">
					<ul class="cf">

					<!-- Article Item -->
					<% @episodes.each do |episode| %>
						<li class="cf">
							<div class="episode_thumbnail">
								<a href="#">
								<%= image_tag episode.episode_thumbnail.url(:medium), class: "current_episode_thumbnail" %>
								</a>
							</div>
							<div class="episode_overview">
								<h2>
									<%= link_to episode.title, podcast_episode_path(@podcast, episode) %>
								</h2>
								<p class="description">
									<%= truncate(episode.description, length: 160) %>
								</p>
							</div>
						</li>
					<% end %>
					<!-- Article Item ends -->

					
					
					</ul>
				</div>
			</div>

				<!-- Pagination -->
				<%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/welcome/index.html.erb
<div id="background">
		<header class="cf">
		<div class="wrapper_wide">
    		<%= link_to t("navbar.logo"), root_path, id: "logo" %>
			<nav>
				<ul>
				<% unless podcast_signed_in? %>
					<li><%= link_to_unless_current "English", locale: "en" %></li> 
					<li><%= link_to_unless_current "العربية", locale: "ar" %></li>
					|
					<li><%= link_to t("navbar.menu.explore"), podcasts_path%></li>
	          		<li><%= link_to t("navbar.menu.signin"), signin_path  %></li>
	          		<li><%= link_to t("navbar.menu.signup"), signup_path %></li>
					<% else %>
				    <li><%= link_to t("navbar.menu.dashboard"), root_path %></li>
		            <li><%= link_to t("navbar.menu.explore"), podcasts_path %></li>
		            <li><%= link_to t("navbar.menu.signout"), destroy_podcast_session_path, method: :delete %>
				<% end %>
				</ul>
			</nav>
		   </div>
		</header>

		<div class="wrapper_skinny">
		<h1><%= t "pages.welcome.title" %></h1>
		<%= link_to t("pages.welcome.btn_cre"), signup_path, class: "button button_highlight" %>
		<%= link_to t("pages.welcome.btn_exp"), podcasts_path, class: "button button_white" %>
		</div>
	</div>

	<div class="wrapper_wide">
		<div id="box">
			<h1>فكرة المنصة</h1>
		</div>
	</div>